project:
  type: website
  output-dir: docs
  resources:
    - charts/

website:
  title: "FareSighted: NYC Green Taxi Trip Analysis"

  sidebar:
    style: "docked"
    search: false
    contents:

      - text: "Introduction"
        href: index.qmd

      - section: "Findings"
        contents:
          - text: "Finding 1: Trip Efficiency Across Time, Boroughs, and Routes"
            href: finding-01.qmd

          - text: "Finding 2: Pickup and Drop-off Imbalances and Service Availability"
            href: finding-02.qmd

          - text: "Finding 3: Congestion, Trip Volume, and Surcharge"
            href: finding-03.qmd

      - section: "Interactive Dashboards"
        contents:
          - text: "Dashboard 1: Trip Efficiency and Satisfaction"
            href: dashboard1.qmd

          - text: "Dashboard 2: Pickup and Drop-off Imbalances"
            href: dashboard2.qmd

          - text: "Dashboard 3: Congestion and Surcharge"
            href: dashboard3.qmd

      - text: "Project Limitations"
        href: limitations.qmd

      - text: "References & Sources"
        href: reference.qmd

format:
  html:
    theme: [cosmo]
    toc: false
    include-in-header:
      - text: |
          <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
          <script src="https://cdn.jsdelivr.net/npm/vega-lite@5"></script>
          <script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
